# ==============================
# Estados del chatbot
# ==============================

MENU = "MENU"
ESPERANDO_OPCION = "ESPERANDO_OPCION"

# Reserva de turno
ESPERANDO_DNI = "ESPERANDO_DNI"
REGISTRANDO_PACIENTE = "REGISTRANDO_PACIENTE"
SELECCIONANDO_FECHA = "SELECCIONANDO_FECHA"
SELECCIONANDO_HORARIO = "SELECCIONANDO_HORARIO"
CONFIRMANDO_RESERVA = "CONFIRMANDO_RESERVA"
REGISTRANDO_TURNO = "REGISTRANDO_TURNO"

# Funciones secundarias
CONSULTANDO_TURNO = "CONSULTANDO_TURNO"
CANCELANDO_TURNO = "CANCELANDO_TURNO"

# Fin
FIN = "FIN"